### ISSUE TITLE
Duplication of events

### ISSUE THREAD

**Issue by dmitryos** [dmitrif/onvif2mqtt#17]
Hi,
Wondering if it is a bug or I'm using the application incorrectly. With the next config from the doc:
```yaml
api:
  templates:
    #Subtopics can be nested with `/` and are interpolated
    - subtopic: ${eventType}/json 
      # Should this message be retained by MQTT
      # Defaults to true
      retain: false
      # Template that should be published to the topic, 
      # values are interpolated
      template: >- 
        { 
          "device": "${onvifDeviceId}", 
          "eventType": "${eventType}", 
          "state": "${eventState}" 
        }
# MQTT Broker configuration, 
# required due to nature of project.
mqtt:
  host: 192.168.X.X
  port: 1883
  username: aaa
  password: bbb
# All of your ONVIF devices
onvif:
  # Name for the device (used in MQTT topic)
  - name: frontcamera
    hostname: 192.168.X.Y
    port: 80
    username: ccc
    password: ddd
  - name: backcamera
    hostname: 192.168.X.Z
    port: 80
    username: eee
    password: fff
```

when one(!) camera triggers an event in the mqtt I receive this event for both(!) cameras (it sends two events with different cameras name).

Probably I can create a docker container for each camera but might be it is just a small change will fix this behaviour.

Thank you,
Dmitry
