### ISSUE TITLE
Support for custom events

### ISSUE THREAD

**Issue by Kepro** [dmitrif/onvif2mqtt#60]
Hello, I have a couple of ReoLink cameras & doorbell :-) 

and they have a lot of custom events e.g.

- `RuleEngine/MyRuleDetector/Visitor` doorbell
- `RuleEngine/MyRuleDetector/FaceDetect` doorbell
- `RuleEngine/MyRuleDetector/PeopleDetect` cam
- `RuleEngine/MyRuleDetector/VehicleDetect` cam
- `RuleEngine/MyRuleDetector/DogCatDetect` cam

I make it work locally (without config), I would like to create PR with config proposal with some mapping e.g.

```yaml
// top level configuration
topics:
  <eventName>: <topicName>
// device level configuration
devices:
  - name: Doorbell
    topics:
      <eventName>: <topicName>
```

any comments before I will create PR? :)
