### ISSUE TITLE
NPM should not be in package.json

### ISSUE THREAD

**Issue by pkasarda** [dmitrif/onvif2mqtt#62]
https://github.com/dmitrif/onvif2mqtt/blob/6585ba2facc708432805643dd3567d0baefb7c18/package.json#L27

in pipeline if you need it use 

```yaml
            - uses: actions/setup-node@v3
              with:
                  node-version: lts/*
                  cache: 'npm'
```
